site_name: clocking
site_url: https://clocking.readthedocs.io/en/latest/
nav:
  - Home: index.md
  - Package: package.md
  - CLI: cli.md
  - Examples: examples.md

markdown_extensions:
  - "admonition"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: true
            show_source: false

theme:
  name: cinder