version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Install prettytable
          command: pip install prettytable
      - run: sudo chmod -R 777 /tmp
      - run:
          name: Run tests
          command: python -m pytest tests

workflows:
  main:
    jobs:
      - build-and-test